input_data_path: "data/raw/heart.csv"
output_model_path: "models/model.pkl"
output_transformer_path: "models/transformer.pkl"
metric_path: "models/metrics.json"
splitting_params:
  val_size: 0.2
  random_state: 42
train_params:
  model_type: "RandomForestClassifier"
  max_depth: 10
  random_state: 42
feature_params:
  categorical_features:
    - 'sex'
    - 'cp'
    - 'fbs'
    - 'restecg'
    - 'exang'
    - 'slope'
    - 'thal'
  numerical_features:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'thalach'
    - 'oldpeak'
    - 'ca'
  target_col: 'target'
